name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: nimble test -y
      - name: Build demo
        run: nim c -d:release --hints:off examples/dashboard.nim
